### ISSUE TITLE
Unable to build it in Linux

### ISSUE THREAD

**Issue by Yaco** [Aluxian/WhatsApp-Desktop#39]
Hi,
i can't find the way to build it. I am trying:

```
yaco@voltron:~/Programas/WhatsApp-Desktop$ gulp pack:linux32
[19:55:03] Requiring external module coffee-script/register

Error: Cannot find module 'merge-stream'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/yaco/Programas/WhatsApp-Desktop/gulpfile.coffee:3:15)
  at Object.<anonymous> (/home/yaco/Programas/WhatsApp-Desktop/gulpfile.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/home/yaco/Programas/WhatsApp-Desktop/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/yaco/Programas/WhatsApp-Desktop/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
  at module.exports (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
  at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
  at /usr/lib/node_modules/gulp/node_modules/liftoff/index.js:159:9
  at /usr/lib/node_modules/gulp/node_modules/v8flags/index.js:91:14
  at /usr/lib/node_modules/gulp/node_modules/v8flags/index.js:38:7
  at process._tickCallback (node.js:415:13)
  at Function.Module.runMain (module.js:499:11)
  at startup (node.js:119:16)
  at node.js:902:3
```

I installed  ```merge-stream``` running ``` sudo npm install -g merge-stream``` but still getting the same error. 

Any help? Thanks!

**Comment by Aluxian** [comment]
Hey, did you do `npm install`?

**Comment by Yaco** [comment]
Yeap, I managed to install al the dependencies. Now I am getting this error:

```
yaco@voltron:~/Programas/WhatsApp-Desktop$ gulp pack:linux64
[20:02:53] Requiring external module coffee-script/register
[20:02:53] Using gulpfile ~/Programas/WhatsApp-Desktop/gulpfile.coffee
[20:02:53] Task 'pack:linux64' is not in your gulpfile
[20:02:53] Please check the documentation for proper gulpfile formatting
````

**Comment by Aluxian** [comment]
The task is called `pack:linux64:deb`.

**Comment by Yaco** [comment]
Thanks Aluxian. You should update the README file since the documentation of that command is outdated.

However, I am still unable to build it:

```
yaco@voltron:~/Programas/WhatsApp-Desktop$ gulp pack:linux64:deb
[10:35:53] Requiring external module coffee-script/register
[10:35:53] Using gulpfile ~/Programas/WhatsApp-Desktop/gulpfile.coffee
[10:35:53] Starting 'build:linux64'...
[10:35:54] 'build:linux64' errored after 881 ms
[10:35:54] Error in plugin 'gulp-node-webkit-builder'
Message:
    Error occured while building app!
```

What can I try?

**Comment by p53ud0k0d3** [comment]
Please update the readme. 
pack:linux64:deb

**Comment by Aluxian** [comment]
@Yaco Sorry for the delay. I don't know what the error could be. I looked at the source code of the `gulp-node-webkit-builder` plugin and instead of throwing the actual error it just sends that unhelpful message -_-

Please go to `node_modules/gulp-node-webkit-builder/index.js` and replace this line:

    _this.emit('error', new PluginError(PLUGIN_NAME, 'Error occured while building app!'));

with this:

    _this.emit('error', err);

And let me know what it prints after trying to build again.

@p53ud0k0d3 Done. Sorry guys, I had the impression it's correct.

**Comment by Yaco** [comment]
I did it, this is the result:

```
yaco@voltron:~/Programas/WhatsApp-Desktop$ gulp pack:linux64:deb
[15:14:43] Requiring external module coffee-script/register
[15:14:44] Using gulpfile ~/Programas/WhatsApp-Desktop/gulpfile.coffee
[15:14:44] Starting 'build:linux64'...
[15:14:44] 'build:linux64' errored after 773 ms
[15:14:44] Error: Please make sure that your project's package.json includes a version and a name value
  at formatError (/usr/lib/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:195:15)
  at Gulp.EventEmitter.emit (events.js:95:17)
  at Gulp.Orchestrator._emitTaskDone (/home/yaco/Programas/WhatsApp-Desktop/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /home/yaco/Programas/WhatsApp-Desktop/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/home/yaco/Programas/WhatsApp-Desktop/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at DestroyableTransform.<anonymous> (/home/yaco/Programas/WhatsApp-Desktop/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4)
  at DestroyableTransform.f (/home/yaco/Programas/WhatsApp-Desktop/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
  at DestroyableTransform.EventEmitter.emit (events.js:117:20)
  at /home/yaco/Programas/WhatsApp-Desktop/node_modules/gulp-node-webkit-builder/index.js:25:16
  at tryCatch1 (/home/yaco/Programas/WhatsApp-Desktop/node_modules/gulp-node-webkit-builder/node_modules/node-webkit-builder/node_modules/bluebird/js/main/util.js:63:19)
  at Promise$_callHandler [as _callHandler] (/home/yaco/Programas/WhatsApp-Desktop/node_modules/gulp-node-webkit-builder/node_modules/node-webkit-builder/node_modules/bluebird/js/main/promise.js:695:13)
  at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/yaco/Programas/WhatsApp-Desktop/node_modules/gulp-node-webkit-builder/node_modules/node-webkit-builder/node_modules/bluebird/js/main/promise.js:711:18)
  at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/yaco/Programas/WhatsApp-Desktop/node_modules/gulp-node-webkit-builder/node_modules/node-webkit-builder/node_modules/bluebird/js/main/promise.js:868:14)
  at Promise$_settlePromises [as _settlePromises] (/home/yaco/Programas/WhatsApp-Desktop/node_modules/gulp-node-webkit-builder/node_modules/node-webkit-builder/node_modules/bluebird/js/main/promise.js:1006:14)
  at Promise$_rejectPromises [as _rejectPromises] (/home/yaco/Programas/WhatsApp-Desktop/node_modules/gulp-node-webkit-builder/node_modules/node-webkit-builder/node_modules/bluebird/js/main/promise.js:999:10)
  at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/yaco/Programas/WhatsApp-Desktop/node_modules/gulp-node-webkit-builder/node_modules/node-webkit-builder/node_modules/bluebird/js/main/async.js:74:12)
  at Async$consumeFunctionBuffer (/home/yaco/Programas/WhatsApp-Desktop/node_modules/gulp-node-webkit-builder/node_modules/node-webkit-builder/node_modules/bluebird/js/main/async.js:37:14)
  at process._tickCallback (node.js:415:13)
```

**Comment by Aluxian** [comment]
Are you sure that `./src/package.json` includes a version and a name? Did you edit them?

**Comment by Yaco** [comment]
I didn't, this is what i got:

```
yaco@voltron:~/Programas/WhatsApp-Desktop$ cat ./src/package.json 
{
  "main": "app.html",
  "name": "UnofficialWhatsApp",
  "version": "",
  "app-id": "com.aluxian.whatsappfordesktop",
  "chromium-args": "--disable-setuid-sandbox",
  "window": {
    "width": 800,
    "height": 600,
    "title": "Unofficial WhatsApp",
    "icon": "images/icon.png",
    "toolbar": false,
    "show": false
  },
  "webkit": {
    "plugin": true
  },
  "dependencies": {
    "async": "^1.0.0",
    "auto-launch": "^0.1.18",
    "jfs": "^0.2.5",
    "request": "^2.56.0",
    "semver": "^4.3.5"
  },
  "manifestUrl": "https://raw.githubusercontent.com/Aluxian/WhatsApp-Desktop/master/src/package.json",
  "packages": {
    "osx64": "https://github.com/Aluxian/WhatsApp-Desktop/releases/download/v/UnofficialWhatsApp.dmg",
    "win32": "https://github.com/Aluxian/WhatsApp-Desktop/releases/download/v/UnofficialWhatsAppSetup.exe",
    "linux32": "https://github.com/Aluxian/WhatsApp-Desktop/releases/download/v/UnofficialWhatsApp_linux32.deb",
    "linux64": "https://github.com/Aluxian/WhatsApp-Desktop/releases/download/v/UnofficialWhatsApp_linux64.deb"
  }
}
```

**Comment by Aluxian** [comment]
Look at `"version": ""`. Write `1.1.0` or any version in there and it should work.

**Comment by jackfido** [comment]
I cant compile it, i need first to run: $sudo npm install -g gulp
ackfido@GoliApp:~/Descargas/WhatsApp-Desktop-master$ sudo npm install -g gulp
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp/bin/gulp.js
gulp@3.9.0 /usr/local/lib/node_modules/gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── semver@4.3.6
├── tildify@1.1.2 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.3.0)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, mkdirp@0.5.1, strip-bom@1.0.0, vinyl@0.4.6, defaults@1.0.3, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, fancy-log@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, vinyl@0.5.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
jackfido@GoliApp:~/Descargas/WhatsApp-Desktop-master$ 


Then after i run: $sudo npm install

I get:
jackfido@GoliApp:~/Descargas/WhatsApp-Desktop-master$ sudo npm install
npm WARN deprecated node-webkit-builder@1.0.13: WARNING: This module has been renamed to nw-builder. Install using nw-builder instead, node-webkit-builder will no longer be updated.
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/jackfido/Descargas/WhatsApp-Desktop-master/node_modules/gulp-appdmg'
npm ERR! error rolling back  gulp-appdmg@1.0.2 { [Error: ENOTEMPTY, rmdir '/home/jackfido/Descargas/WhatsApp-Desktop-master/node_modules/gulp-appdmg']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/home/jackfido/Descargas/WhatsApp-Desktop-master/node_modules/gulp-appdmg' }
npm WARN optional dep failed, continuing gulp-appdmg@1.0.2
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hawk@3.1.0: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine boom@2.10.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN cannot run in wd UnofficialWhatsApp@1.1.0 (cd src && npm install) (wd=/home/jackfido/Descargas/WhatsApp-Desktop-master)
run-sequence@1.1.4 node_modules/run-sequence
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, fancy-log@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, vinyl@0.5.3, lodash.template@3.6.2, gulplog@1.0.0, multipipe@0.1.2, through2@2.0.0, dateformat@1.0.11)

gulp-uglify@1.4.2 node_modules/gulp-uglify
├── uglify-save-license@0.4.1
├── deap@1.0.0
├── isobject@2.0.0 (isarray@0.0.1)
├── through2@2.0.0 (readable-stream@2.0.3, xtend@4.0.0)
├── vinyl-sourcemaps-apply@0.2.0 (source-map@0.5.3)
├── fancy-log@1.1.0 (chalk@1.1.1, dateformat@1.0.11)
├── uglify-js@2.5.0 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.5.3)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, beeper@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, lodash.template@3.6.2, vinyl@0.5.3, gulplog@1.0.0, minimist@1.2.0, chalk@1.1.1, multipipe@0.1.2, dateformat@1.0.11)

gulp-github-release@1.0.3 node_modules/gulp-github-release
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── gulp-util@3.0.7 (lodash._reescape@3.0.0, fancy-log@1.1.0, array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, chalk@1.1.1, lodash.template@3.6.2, gulplog@1.0.0, vinyl@0.5.3, minimist@1.2.0, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
└── publish-release@1.1.0 (single-line-log@0.4.1, mime@1.3.4, pkginfo@0.3.1, string-editor@0.1.2, async@0.9.2, minimist@1.2.0, github-url-to-object@1.6.0, progress-stream@1.1.1, ghauth@2.0.1, pretty-bytes@1.0.4, request@2.65.0, lodash@3.10.1, inquirer@0.8.5)

gulp-node-webkit-builder@1.1.1 node_modules/gulp-node-webkit-builder
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, fancy-log@1.1.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, lodash._reescape@3.0.0, has-gulplog@0.1.0, vinyl@0.5.3, lodash.template@3.6.2, chalk@1.1.1, gulplog@1.0.0, minimist@1.2.0, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
└── node-webkit-builder@1.0.13 (platform-overrides@1.0.1, inherits@2.0.1, progress@1.1.8, rcedit@0.2.0, temp@0.7.0, semver@2.3.2, optimist@0.6.1, rimraf@2.4.3, simple-glob@0.1.0, graceful-fs-extra@1.0.6, bluebird@1.2.4, graceful-ncp@2.0.0, request@2.40.0, winresourcer@0.9.0, decompress-zip@0.0.8, lodash@2.4.2, tar-fs@0.3.3, archiver@0.13.1, plist@1.1.0, update-notifier@0.1.10)


and finally i cant run 
jackfido@GoliApp:~/Descargas/WhatsApp-Desktop-master$ gulp pack:linux64:deb/usr/bin/env: node: No existe el archivo o el directorio

Can anyone help me....
I am using ubuntu 15.10 64 bits

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
